laguage: java
jdk: oraclejdk9
install: mvn -s travis-mvn-settings.xml -D skipTests package
script: mvn -s travis-mvn-settings.xml verify
deploy:
  provider: script
  script: mvn -s travis-mvn-settings.xml clean deploy
  on: {branch: master}
