laguage: java
jdk: oraclejdk9
install: mvn -D skipTests package
script: mvn verify
deploy:
  provider: script
  script: mvn --settings travis-mvn-settings.xml -P sonatype clean deploy
  on: {branch: master}
